import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, Archive, CalendarDays, Loader2, Sparkles } from "lucide-react";
import { useLocation } from "wouter";

export default function History() {
  const [, setLocation] = useLocation();
  const { data: campaigns, isLoading } = trpc.campaign.list.useQuery();
  return <div className="min-h-screen text-white pulse-grid"><header className="border-b border-white/[.07] px-6 py-5 sm:px-9"><p className="text-[10px] font-bold uppercase tracking-[.24em] text-rose-200/70">Your work</p><h1 className="mt-1 font-display text-3xl tracking-tight">Campaign library</h1></header><main className="mx-auto w-full max-w-[1280px] px-5 py-9 sm:px-8"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="font-display text-4xl">Every campaign, ready to revisit.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/55">Your creative assets, insights, copy directions, and saved export packages remain organised by campaign.</p></div><Button onClick={() => setLocation("/")} className="bg-rose-200 text-[#2a1e31] hover:bg-rose-100"><Sparkles className="mr-2 h-4 w-4" />New campaign</Button></div>{isLoading ? <div className="grid min-h-[300px] place-items-center"><Loader2 className="h-6 w-6 animate-spin text-rose-200" /></div> : campaigns?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{campaigns.map(campaign => <button key={campaign.id} onClick={() => setLocation(`/?campaign=${campaign.id}`)} className="group rounded-[24px] border border-white/[.09] bg-[#171521]/85 p-5 text-left transition hover:-translate-y-1 hover:border-rose-200/35 hover:bg-[#1d1929]"><div className="flex items-start justify-between"><span className="rounded-full border border-white/10 bg-white/[.035] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.13em] text-white/50">{campaign.status}</span><ArrowUpRight className="h-4 w-4 text-white/35 transition group-hover:text-rose-200" /></div><h3 className="mt-8 font-display text-2xl">{campaign.campaignName || campaign.productName}</h3><p className="mt-2 text-sm text-white/50">{campaign.industry}</p><div className="mt-8 flex items-center justify-between border-t border-white/[.07] pt-4 text-xs text-white/42"><span className="flex items-center gap-2"><CalendarDays className="h-3.5 w-3.5" />{new Date(campaign.updatedAt).toLocaleDateString()}</span><span>{campaign.exportUrl ? "Export saved" : "Open pack"}</span></div></button>)}</div> : <div className="grid min-h-[380px] place-items-center rounded-[28px] border border-dashed border-white/15 bg-white/[.02] p-8 text-center"><div><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-white/[.05] text-rose-200"><Archive className="h-5 w-5" /></span><h3 className="mt-5 font-display text-3xl">No campaign history yet.</h3><p className="mt-3 max-w-sm text-sm leading-6 text-white/50">Start with a considered brief and your complete campaign pack will appear here.</p><Button onClick={() => setLocation("/")} className="mt-6 bg-white text-[#241d2d] hover:bg-rose-50">Create a campaign</Button></div></div>}</main></div>;
}
